### ISSUE TITLE
BUSCO version and databases across datasets

### ISSUE THREAD

**Issue by talioto** [ERGA-consortium/EARs#119]
I noticed that if different versions are used for different assemblies, the EAR gives a warning saying so. Can you just report the version and db used per result, please? I'd rather be able to see it than see "Warning: BUSCO versions or lineage datasets are not the same across results"

**Comment by diegomics** [comment]
Should be fixed from now on: https://github.com/ERGA-consortium/EARs/commit/9fbcf0b9657caf153d6e70e7ace1f684ee242e16

When something is different across assemblies it shows this:

<img width="788" alt="Screenshot 2024-11-19 at 13 58 28" src="https://github.com/user-attachments/assets/353c3192-24bb-4ec7-a3d6-8ef4e77f721b">

Otherwise shows only one line. I will check if the yaml parser is processing it properly. Thanks for reminding me to update this 🙏
